import turtle

pen = turtle.Turtle()
screen = turtle.Screen()

screen.bgcolor("LightSteelBlue")

#ground
pen.up()
pen.goto(-200,-130)
pen.down()
pen.fillcolor("brown")
pen.begin_fill()
pen.forward(400)
pen.right(90)
pen.forward(75)
pen.right(90)
pen.forward(400)
pen.right(90)
pen.forward(75)
pen.end_fill()
pen.up()
pen.right(90)
pen.goto(-200,-167.5)
pen.down()
pen.forward(400)
pen.up()
pen.goto(-200,-130)
for i in range(20):
  pen.up()
  pen.forward(20)
  pen.down()
  pen.right(90)
  pen.forward(75)
  pen.backward(75)
  pen.left(90)
  
#pipes
def pipe(x,y,forward):
 pen.up()
 pen.left(90)
 pen.goto(x,y)
 pen.down()
 pen.fillcolor("chartreuse")
 pen.begin_fill()
 pen.forward(forward)
 pen.left(90)
 pen.forward(17)
 pen.right(90)
 pen.forward(25)
 pen.right(90)
 pen.forward(75)
 pen.right(90)
 pen.forward(25)
 pen.right(90)
 pen.forward(17)
 pen.left(90)
 pen.forward(forward)
 pen.right(90)
 pen.forward(50)
 pen.end_fill()


#lucky blocks
def lucky(x,y):
  pen.up()
  pen.goto(x,y)
  pen.fillcolor("goldenrod")
  pen.begin_fill()
  pen.down()
  for i in range(4):
    pen.forward(40)
    pen.right(90)
  pen.end_fill()
  pen.up()
  pen.forward(20)
  pen.right(90)
  pen.forward(30)
  pen.right(180)
  pen.down()
  pen.color("black")
  pen.write("?", None, "center", " 20pt bold")
#bricks
def brick(x,y) :
  pen.up()
  pen.goto(x,y)
  pen.fillcolor("sienna")
  pen.down()
  pen.begin_fill()
  for i in range(4):
    pen.forward(40)
    pen.right(90)
  pen.forward(20)
  pen.right(90)
  pen.forward(10)
  pen.left(90)
  pen.forward(20)
  pen.backward(40)
  pen.forward(10)
  pen.right(90)
  pen.forward(20)
  pen.left(90)
  pen.backward(10)
  pen.forward(30)
  pen.left(90)
  pen.forward(20)
  pen.backward(20)
  pen.right(90)
  pen.forward(10)
  pen.backward(20)
  pen.right(90)
  pen.forward(10)
  pen.end_fill()
#coins

def coin(x,y) :
  pen.up()
  pen.goto(x,y)
  pen.down()
  pen.fillcolor("gold")
  pen.begin_fill()
  pen.circle(17)
  pen.end_fill() 
  pen.up()
  pen.backward(5)
  pen.left(90)
  pen.forward(9)
  pen.down()
  pen.fillcolor("darkgoldenrod")
  pen.begin_fill()
  for i in range(2) :
    pen.forward(17)
    pen.right(90)
    pen.forward(10)
    pen.right(90)
  pen.end_fill()
#bushes
def bush(x,y) :
 pen.up()
 pen.goto(x,y)
 pen.down()
 pen.fillcolor("lime")
 pen.begin_fill()
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.right(100)
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.right(108)
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.forward(50)
 pen.end_fill()
 
 #cloud
def cloud(x,y) :
 pen.up()
 pen.goto(x,y)
 pen.down()
 pen.fillcolor("Aliceblue")
 pen.begin_fill()
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.right(100)
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.right(187)
 for i in range(18) :
  pen.forward(3)
  pen.left(10.5)
 pen.right(189)
 for i in range(18) :
  pen.forward(3)
  pen.left(10.5)
 pen.right(110)
 for i in range(18) :
   pen.forward(3)
   pen.left(10.5)
 pen.forward(100)
 pen.end_fill()
 
#placement
bush(-130,-130)
pipe(-90,-130,50)
pen.left(180)
pipe(40,-130,75)
pen.right(180)
bush(140,-130)
pen.left(2)
brick(-130,50)
pen.left(90)
brick(-90,50)
pen.left(90)
lucky(-50,50)
pen.left(90)
coin(-30,85)
pen.left(90)
brick(-10,50)
pen.left(90)
lucky(30,50)
pen.right(90)
cloud(-30,100)
cloud(170,130)

